services:
  - type: web
    plan: free
    name: agency
    runtime: python
    repo: https://github.com/fvilpaz/agency.git
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
